"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['__init__.py']
DATA_FILES = ['--iconfile', '--resources', 'icon.png', '--plist']
OPTIONS = {'iconfile': '/Users/b2550/Desktop/TIMARA-Inventory-Management-System/client/icon.icns',
 'plist': {'CFBundleDisplayName': 'Inventory Manager',
           'CFBundleIdentifier': 'net.squizit.inventorymanager',
           'CFBundleName': 'Inventory Manager',
           'CFBundleVersion': 'ALPHA 0.1',
           'LSUIElement': True,
           'NSHumanReadableCopyright': '© Ben Saltz 2018',
           'UIRequiresPersistentWiFi': True}}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
