language: python

python:
  - "3.4"

matrix:
    include:
        - os: osx
          language: generic
        - os: linux
          language: python

before_install: ./scripts/before-install.sh

install:
  - pip3 install pipenv

script:
  - ./scripts/build-client.sh
  - ./scripts/build-server.sh
